/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#301400",
        "on-primary-fixed": "#001d35",
        "secondary-container": "#d4e1f5",
        "primary-container": "#0073bb",
        "primary-fixed-dim": "#9ccaff",
        "inverse-primary": "#9ccaff",
        "on-secondary-fixed-variant": "#3c4858",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d7dbdb",
        "on-primary": "#ffffff",
        "primary": "#005a94",
        "primary-fixed": "#d0e4ff",
        "on-surface-variant": "#404751",
        "on-primary-fixed-variant": "#00497a",
        "outline": "#707882",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eef1f1",
        "on-secondary-fixed": "#101c2b",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bbc7db",
        "on-primary-container": "#edf4ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#576474",
        "on-background": "#181c1d",
        "surface-container": "#ebeeee",
        "inverse-surface": "#2d3131",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#703800",
        "surface-container-low": "#f1f4f4",
        "on-error": "#ffffff",
        "secondary": "#535f70",
        "tertiary-fixed": "#ffdcc4",
        "on-surface": "#181c1d",
        "on-tertiary-container": "#fff0e8",
        "outline-variant": "#c0c7d2",
        "surface": "#f7fafa",
        "secondary-fixed": "#d7e3f7",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ab5901",
        "surface-container-highest": "#e0e3e3",
        "surface-tint": "#0062a0",
        "surface-bright": "#f7fafa",
        "tertiary": "#874500",
        "surface-container-high": "#e6e9e9",
        "tertiary-fixed-dim": "#ffb781",
        "background": "#f7fafa",
        "surface-variant": "#e0e3e3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-margin": "32px",
        "container-padding": "24px",
        "card-gap": "20px",
        "gutter": "16px",
        "unit": "4px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "display-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "code": ["13px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
