name: Receipt Vault CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: receipt-vault-frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: receipt-vault-frontend
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::887395463967:role/ReceiptVaultGitHubDeployRole
          aws-region: ap-south-2
          role-session-name: GitHubActions

      - name: Load deployment configuration from SSM
        run: |
          echo "FRONTEND_BUCKET=$(aws ssm get-parameter --name /receipt-vault/frontend-bucket --query 'Parameter.Value' --output text)" >> $GITHUB_ENV

          echo "CLOUDFRONT_DISTRIBUTION_ID=$(aws ssm get-parameter --name /receipt-vault/cloudfront-distribution-id --query 'Parameter.Value' --output text)" >> $GITHUB_ENV

          echo "VITE_API_BASE_URL=$(aws ssm get-parameter --name /receipt-vault/api-base-url --query 'Parameter.Value' --output text)" >> $GITHUB_ENV

          echo "VITE_COGNITO_AUTHORITY=$(aws ssm get-parameter --name /receipt-vault/cognito-authority --query 'Parameter.Value' --output text)" >> $GITHUB_ENV

          echo "VITE_COGNITO_CLIENT_ID=$(aws ssm get-parameter --name /receipt-vault/cognito-client-id --query 'Parameter.Value' --output text)" >> $GITHUB_ENV

          echo "VITE_COGNITO_DOMAIN=$(aws ssm get-parameter --name /receipt-vault/cognito-domain --query 'Parameter.Value' --output text)" >> $GITHUB_ENV


      - name: Run ESLint
        working-directory: receipt-vault-frontend
        run: npm run lint

      - name: Build React App
        working-directory: receipt-vault-frontend
        run: npm run build


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip




      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: Package Upload Lambda
        run: |
            mkdir -p artifacts/upload-lambda
            pip install -r receipt-vault-backend/upload-lambda/requirements.txt \
            -t artifacts/upload-lambda

            cp receipt-vault-backend/upload-lambda/*.py artifacts/upload-lambda/

            cd artifacts/upload-lambda
            zip -r ../../upload-lambda.zip .
      - name: Package Processor Lambda
        run: |
            mkdir -p artifacts/processor-lambda
            pip install -r receipt-vault-backend/processor-lambda/requirements.txt \
            -t artifacts/processor-lambda

            cp receipt-vault-backend/processor-lambda/*.py artifacts/processor-lambda/

            cd artifacts/processor-lambda
            zip -r ../../processor-lambda.zip .
      - name: Package Receipts API Lambda
        run: |
            mkdir -p artifacts/receipts-apis
            pip install -r receipt-vault-backend/receipts-apis/requirements.txt \
            -t artifacts/receipts-apis

            cp receipt-vault-backend/receipts-apis/*.py artifacts/receipts-apis/

            cd artifacts/receipts-apis
            zip -r ../../receipts-apis.zip .

      - name: Upload Lambda Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-packages
          path: |
            upload-lambda.zip
            processor-lambda.zip
            receipts-apis.zip

      - name: Deploy React App to S3
        run: |
            aws s3 sync receipt-vault-frontend/dist/ s3://${{ env.FRONTEND_BUCKET }} \
              --delete
      - name: Invalidate CloudFront Cache
        run: |
            aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
      


